services:
  # Servicio PHP-FPM
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: products_php
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - JWT_SECRET=MiSuperSecretKeyParaDistributed2025System!
      - JWT_TTL=60
      - JWT_ALGO=HS256
    volumes:
      - ./src:/var/www
    networks:
      - products_network
    depends_on:
      postgres:
        condition: service_healthy

  # Servicio Nginx
  nginx:
    image: nginx:alpine
    container_name: products_nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - products_network
    depends_on:
      - php

  # Servicio PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: products_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - products_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U products_user -d products_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  products_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local