
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - RUST_LOG=info
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_DATABASE=inventario_db
      - DB_PORT=5432
      - PORT=5002

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - inventario-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=inventario_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventario_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - inventario-network

volumes:
  postgres_data:

networks:
  inventario-network:
    driver: bridge